### ISSUE TITLE
failed to load vendor/autoload.php

### ISSUE THREAD

**Issue by TumiDebrah** [SymfonyTest/SymfonyDependencyInjectionTest#104]
I just started reading the laravel 5.6 docs and php is not my forte I am still learning so try to use a lot of sample projects to learn but I cant seem to get the server up found a solution but unfortunately works on 
an older version of php ^5.5.0 they said to use composer install and composer update but fix doesnt work for php 7 am using 7.2.6

**Comment by Nyholm** [comment]
Hey. 
I’m going to give you a quick answer and then refer you to other sources where you can get help. Github issue trackers is meant for bugs with a specific library. 

You should run “composer update”, that will create the auto loading files for you. Php versions do not matter. 

Please ask future questions on StackOverflow or similar websites.
