### ISSUE TITLE
Support for Symfony 5

### ISSUE THREAD

**Issue by garak** [SymfonyTest/SymfonyDependencyInjectionTest#123]

**Comment by lolautruche** [comment]
We'd actually only need a new tag since `composer.json` already allows Symfony 5

#SymfonyHackday

**Comment by Nyholm** [comment]
Here is the new tag: 
https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/releases/tag/4.1.0

**Comment by lolautruche** [comment]
Thank you @Nyholm !
