### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by aurimasrimkusnfq** [SymfonyTest/SymfonyDependencyInjectionTest#156]
There a some [changes](https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/compare/5.0.0...master) in main that are not released.
Could you release a new version? :pray:

**Comment by aurimasrimkusnfq** [comment]
@Nyholm

**Comment by Nyholm** [comment]
Ping @stloyd. You merged most of the new PRs. Do you want to take care of next release?

**Comment by stloyd** [comment]
Just released `5.1.0`: https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/releases/tag/5.1.0
