### ISSUE TITLE
it_lower_cases_aliased_service_ids fails

### ISSUE THREAD

**Issue by rejinka** [SymfonyTest/SymfonyDependencyInjectionTest#80]
The test fails, because ContainerBuilder::getAlias() does not lower the given string anymore since 3.3.

**Comment by Nyholm** [comment]
This is correct. That test was removed in https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/pull/87

Thank you for reporting this.

**Comment by rejinka** [comment]
👍
