### ISSUE TITLE
Add phpunit as a non-dev depedency.

### ISSUE THREAD

**Issue by frankdejonge** [SymfonyTest/SymfonyDependencyInjectionTest#94]
Since this package itself will be installed as a --dev dependency I think it makes sense to require phpunit in the main require list, ensuring it's usable when installed.

I'll happily PR this when/if agreed to this proposal.

**Comment by delboy1978uk** [comment]
Just PR'ed that here https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/pull/96

**Comment by Nyholm** [comment]
Fixed by #99
